version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - windows

# this is how to allow failing jobs in the matrix
# environment:
#   matrix:
#     CONFIG: Release
#     ENABLE_MPI: ON
      #fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

install:
# Install MS-MPI
- ps: Start-FileDownload 'https://download.microsoft.com/download/B/2/E/B2EB83FE-98C2-4156-834A-E1711E6884FB/MSMpiSetup.exe'
- MSMpiSetup.exe -unattend
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

# Install MS-MPI SDK
- ps: Start-FileDownload 'https://download.microsoft.com/download/B/2/E/B2EB83FE-98C2-4156-834A-E1711E6884FB/msmpisdk.msi'
- msmpisdk.msi /passive

before_build:
- mkdir build
- cd build
- ls "C:/Program Files (x86)/Microsoft SDKs/MPI"

build_script:
- cmake ../ -DPIDX_BUILD_EXAMPLES=ON -DMPI_HOME="C:/Program Files (x86)/Microsoft SDKs/MPI" -DMPI_C_INCLUDE_PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include" -DMPI_C_LIBRARIES="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x86/msmpi.lib" -DMPI_CXX_INCLUDE_PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include"  -DMPI_CXX_LIBRARIES="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x86/msmpi.lib"
- cmake ../ --build idx_read
- cmake ../ --build idx_write
